name: Main Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  main:
    name: Main Workflow Job
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven Unit Tests
        run: mvn -B test

      - name: Maven It Tests
        run: mvn -B integration-test -Dit.only

      - name: Maven Packaging
        run: mvn -B package -DskipTests