name: Main Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  main:
    name: Main Workflow Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Protoc
        with:
          version: '3.9.1'
        uses: arduino/setup-protoc@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'

      - name: Gradle Compile
        run: ./gradlew compileJava --no-daemon -Dorg.gradle.console=plain

      - name: Gradle Unit Tests
        run: ./gradlew test --no-daemon -Dorg.gradle.console=plain

      #- name: Gradle It Tests
      #  run: ./gradlew it --no-daemon -Dorg.gradle.console=plain

      - name: Gradle Packaging
        run: ./gradlew jar --no-daemon -Dorg.gradle.console=plain